version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_x_clone
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: prisma_user
      MYSQL_PASSWORD: prisma_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: